import { getDocument } from "pdfjs-dist/legacy/build/pdf.mjs";
import { createCanvas } from "@napi-rs/canvas";

const NVIDIA_URL = "https://integrate.api.nvidia.com/v1/chat/completions";
const NVIDIA_MODEL = process.env.NVIDIA_MODEL || "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning";
const MAX_PAGE_CALLS = Math.max(1, Math.min(4, Number(process.env.NVIDIA_PAGE_CONCURRENCY || 2)));
const PAGE_SCALE = Number(process.env.NVIDIA_PDF_SCALE || 1.5);
const PAGE_TEXT_LIMIT = Number(process.env.NVIDIA_PAGE_TEXT_LIMIT || 18000);
const MAX_FINAL_TEXT = Number(process.env.NVIDIA_FINAL_TEXT_LIMIT || 180000);
const REQUEST_TIMEOUT = Number(process.env.NVIDIA_TIMEOUT_MS || 180000);
const nativeFetch = globalThis.fetch.bind(globalThis);
let active = 0;
const queue: (() => void)[] = [];
async function limit<T>(fn: () => Promise<T>): Promise<T> { if (active >= MAX_PAGE_CALLS) await new Promise<void>(r => queue.push(r)); active++; try { return await fn(); } finally { active--; queue.shift()?.(); } }
function key() { const k = process.env.NVIDIA_API_KEY?.trim(); if (!k) throw new Error("NVIDIA_API_KEY is missing on the backend"); return k; }
async function nvidia(body: any, signal?: AbortSignal) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT); const abort = () => controller.abort(); signal?.addEventListener("abort", abort, { once: true }); try { const r = await nativeFetch(NVIDIA_URL, { method:"POST", headers:{Authorization:`Bearer ${key()}`,"Content-Type":"application/json",Accept:"application/json"}, body:JSON.stringify(body), signal:controller.signal }); const data:any=await r.json().catch(()=>({})); if(!r.ok) throw new Error(data?.error?.message||data?.message||`NVIDIA HTTP ${r.status}`); return data; } finally { clearTimeout(timer); signal?.removeEventListener("abort", abort); } }
function dataFromFilePart(part:any) { const raw=part?.file?.file_data||part?.file_data||part?.url; if(typeof raw!=="string")return null; const i=raw.indexOf("base64,"); return i>=0?raw.slice(i+7):raw; }
async function pdfPages(base64:string) { const pdf:any=await getDocument({data:new Uint8Array(Buffer.from(base64,"base64")),disableWorker:true,useSystemFonts:true}).promise; const pages:any[]=[]; for(let i=1;i<=pdf.numPages;i++){ const p:any=await pdf.getPage(i); const tc:any=await p.getTextContent(); const text=(tc.items||[]).map((x:any)=>x?.str||"").join(" ").replace(/\s+/g," ").trim(); if(text.length>=60){pages.push({page:i,text:text.slice(0,PAGE_TEXT_LIMIT)});continue;} const viewport=p.getViewport({scale:PAGE_SCALE}); const canvas:any=createCanvas(Math.ceil(viewport.width),Math.ceil(viewport.height)); await p.render({canvasContext:canvas.getContext("2d"),viewport}).promise; pages.push({page:i,text,image:`data:image/png;base64,${canvas.toBuffer("image/png").toString("base64")}`}); } return pages; }
async function imageToText(page:any,system:string,instruction:string,signal?:AbortSignal){ const data:any=await limit(()=>nvidia({model:NVIDIA_MODEL,messages:[{role:"system",content:system},{role:"user",content:[{type:"text",text:`Read this insurance policy page exactly. Extract all visible text, tables, headings, policy numbers, dates, amounts, names and clauses. Do not invent unreadable text. Preserve numbers and symbols. Page ${page.page}. ${instruction||""}`},{type:"image_url",image_url:{url:page.image}}]}],max_tokens:12000,temperature:0,chat_template_kwargs:{enable_thinking:false},stream:false},signal)); return String(data?.choices?.[0]?.message?.content||""); }
function extractParts(body:any){ const messages=Array.isArray(body?.messages)?body.messages:[]; const system=String(messages.find((m:any)=>m.role==="system")?.content||""); const user=messages.find((m:any)=>m.role==="user"); const parts=Array.isArray(user?.content)?user.content:[]; const file=parts.find((p:any)=>p?.type==="file"); const text=parts.filter((p:any)=>p?.type==="text").map((p:any)=>String(p.text||"")).join("\n"); return {system,text,file,fileBase64:dataFromFilePart(file)}; }
async function handle(body:any,signal?:AbortSignal){ const {system,text,fileBase64}=extractParts(body); if(!fileBase64)throw new Error("NVIDIA bridge could not find the uploaded PDF data"); const pages=await pdfPages(fileBase64); const imagePages=pages.filter(p=>p.image); const imageTexts=await Promise.all(imagePages.map(p=>imageToText(p,system,text,signal))); let documentText=pages.map(p=>`[PAGE ${p.page}]\n${p.text||""}`).join("\n\n"); imagePages.forEach((p,i)=>{documentText=documentText.replace(`[PAGE ${p.page}]\n${p.text||""}`,`[PAGE ${p.page}]\n${imageTexts[i]||p.text||""}`);}); documentText=documentText.slice(0,MAX_FINAL_TEXT); const final:any=await nvidia({model:NVIDIA_MODEL,messages:[{role:"system",content:system},{role:"user",content:`${text}\n\nUse the following complete page-by-page text extracted from the uploaded insurance policy. Return ONLY the JSON object required by the system schema. Do not invent values.\n\n${documentText}`}],max_tokens:Number(process.env.NVIDIA_MAX_TOKENS||12000),temperature:0,chat_template_kwargs:{enable_thinking:false},stream:false},signal); const content=final?.choices?.[0]?.message?.content; if(!content)throw new Error("NVIDIA returned an empty policy analysis"); return {content:String(content),model:NVIDIA_MODEL,usage:final?.usage||null,pages:pages.length,ocrPages:imagePages.length}; }
const originalFetch=globalThis.fetch;
globalThis.fetch=(async(input:RequestInfo|URL,init?:RequestInit)=>{ const url=typeof input==="string"?input:input instanceof URL?input.toString():input.url; if(!url.startsWith("https://openrouter.ai/api/v1/chat/completions"))return originalFetch(input,init); let body:any={}; try{body=typeof init?.body==="string"?JSON.parse(init.body):{};}catch{return originalFetch(input,init);} if(!body?.messages?.some((m:any)=>Array.isArray(m.content)&&m.content.some((p:any)=>p?.type==="file")))return originalFetch(input,init); try{const r=await handle(body,init?.signal||undefined);return new Response(JSON.stringify({id:`nvidia-${Date.now()}`,object:"chat.completion",model:r.model,choices:[{index:0,message:{role:"assistant",content:r.content},finish_reason:"stop"}],usage:r.usage,nvidia:{pages:r.pages,ocrPages:r.ocrPages}}),{status:200,headers:{"Content-Type":"application/json"}});}catch(e:any){return new Response(JSON.stringify({error:{message:e?.message||"NVIDIA scan failed",type:"nvidia_error"}}),{status:502,headers:{"Content-Type":"application/json"}});}}) as typeof globalThis.fetch;
void import("./server.ts").catch((error) => { console.error("Failed to start V-SHIROYA backend:", error); process.exit(1); });
