import express from "express";
import path from "node:path";
import fs from "node:fs";
import dotenv from "dotenv";
dotenv.config();

const app = express();
const PORT = Number(process.env.PORT || 3000);
const ROOT = process.env.APP_ROOT ? path.resolve(process.env.APP_ROOT) : (fs.existsSync(path.join(process.cwd(), "index.html")) ? process.cwd() : path.resolve(__dirname, ".."));
const DIST = path.join(ROOT, "dist");
const DIST_INDEX = path.join(DIST, "index.html");
const DATA_FILE = path.join(ROOT, "policies_db.json");
const AUDIT_FILE = path.join(ROOT, "security_audit.json");
const MAX_BODY = process.env.MAX_BODY_SIZE || "110mb";
const MAX_FILE_BYTES = Number(process.env.MAX_FILE_BYTES || 100 * 1024 * 1024);
const FAST_MODE = process.env.OPENROUTER_FAST_MODE !== "false";
const AI_ENSEMBLE_SIZE = Math.max(1, Math.min(2, Number(process.env.AI_ENSEMBLE_SIZE || (FAST_MODE ? 1 : 2))));
const BULK_CONCURRENCY = Math.max(1, Math.min(6, Number(process.env.BULK_CONCURRENCY || (FAST_MODE ? 4 : 3))));
const USE_PDF_PLUGIN = process.env.OPENROUTER_USE_PDF_PLUGIN === "true";

app.disable("x-powered-by");
const normalizeOrigin=(v?:string)=>String(v||"").trim().replace(/\/$/,"");
const CORS_ALLOW_ALL=process.env.CORS_ALLOW_ALL!=="false";
const allowedOrigins=new Set([process.env.APP_URL,process.env.FRONTEND_URL,process.env.FIREBASE_APP_URL,"https://v-shiroya-insurance.web.app","https://v-shiroya-insurance.firebaseapp.com","https://v-shiroya-policy.web.app","https://v-shiroya-policy.firebaseapp.com","https://v-shiroya-policy.onrender.com","http://localhost:3000","http://localhost:5173"].map(normalizeOrigin).filter(Boolean));
app.use((req,res,next)=>{const origin=normalizeOrigin(req.headers.origin);const allowed=CORS_ALLOW_ALL||!origin||allowedOrigins.has(origin);if(CORS_ALLOW_ALL)res.setHeader("Access-Control-Allow-Origin","*");else if(origin&&allowed){res.setHeader("Access-Control-Allow-Origin",origin);res.append("Vary","Origin");}res.setHeader("Access-Control-Allow-Methods","GET,POST,OPTIONS");res.setHeader("Access-Control-Allow-Headers","Content-Type, Authorization, X-Requested-With");res.setHeader("Access-Control-Max-Age","86400");if(req.method==="OPTIONS")return allowed?res.status(204).end():res.status(403).json({error:"CORS origin not allowed"});next();});
app.use(express.json({limit:MAX_BODY}));
app.use(express.urlencoded({limit:MAX_BODY,extended:true}));

function readJson<T>(file:string,fallback:T):T{try{return fs.existsSync(file)?JSON.parse(fs.readFileSync(file,"utf8")) as T:fallback;}catch(e){console.error(`Failed to read ${file}:`,e);return fallback;}}
function writeJson(file:string,value:unknown){try{fs.writeFileSync(file,JSON.stringify(value,null,2),"utf8");}catch(e){console.error(`Failed to write ${file}:`,e);}}
function addAuditLog(action:string,details:string,req:express.Request){const logs=readJson<any[]>(AUDIT_FILE,[]);logs.unshift({id:`sec-${Date.now()}`,timestamp:new Date().toISOString(),action,actor:"V SHIROYA AI",details,ipAddress:req.ip||"unknown"});writeJson(AUDIT_FILE,logs.slice(0,100));}
function cleanJson(text:string):any{const s=String(text||"").replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim();try{return JSON.parse(s);}catch{const a=s.indexOf("{"),b=s.lastIndexOf("}");if(a>=0&&b>a)return JSON.parse(s.slice(a,b+1));throw new Error("AI returned invalid JSON");}}
function getOpenRouterKeys(){const names=["OPENROUTER_API_KEY","OPENROUTER_API_KEY_1","OPENROUTER_API_KEY_2","OPENROUTER_API_KEY_3","OPENROUTER_API_KEY_4","OPENROUTER_API_KEY_5"];return names.map(name=>({name,value:process.env[name]?.trim()||""})).filter(x=>x.value&&!x.value.startsWith("MY_"));}
function modelsToTry(){const allowPaid=process.env.OPENROUTER_ALLOW_PAID==="true";const configured=(process.env.OPENROUTER_MODELS||process.env.OPENROUTER_MODEL||"openrouter/free").split(",").map(x=>x.trim()).filter(Boolean);const models=allowPaid?configured:configured.filter(m=>m==="openrouter/free"||m.endsWith(":free"));return models.length?models:["openrouter/free"];}

const SCHEMA=`{"documentType":string,"detectedInsurer":string|null,"ownerName":string|null,"policyNumber":string|null,"providerCompany":string|null,"policyType":string|null,"category":string|null,"startDate":string|null,"endDate":string|null,"premiumAmount":number|null,"premiumFrequency":string|null,"sumAssured":number|null,"insuredPerson":string|null,"nominee":string|null,"nomineeRelationship":string|null,"phoneNumber":string|null,"email":string|null,"address":string|null,"dateOfBirth":string|null,"agentName":string|null,"agentPhone":string|null,"branchName":string|null,"paymentMode":string|null,"policyStatus":"ACTIVE"|"EXPIRING SOON"|"EXPIRED","maturityDate":string|null,"additionalDetails":[{"label":string,"value":string}],"missingFields":string[],"uncertainFields":string[],"confidence":number,"extractedText":string,"fieldConfidenceMap":object}`;
const SYSTEM_PROMPT=`You are V Shiroya Policy AI, an expert insurance document extraction engine. Read the COMPLETE document. Identify the exact policy type from the policy schedule and document evidence. Never label a specific policy as General Insurance when a specific category is supported. Valid categories include Motor / Vehicle Insurance, Car Insurance, Two-Wheeler Insurance, Commercial Vehicle Insurance, Life Insurance, Term Life Insurance, Health Insurance, Family Floater Health Insurance, Travel Insurance, Home / Property Insurance, Fire Insurance, Marine Insurance, Personal Accident Insurance, Crop Insurance, Liability Insurance, Commercial Insurance, and General Insurance only when no more specific category is supported. Use explicit policy type/category text first; then corroborate with document evidence. Never invent values. Preserve exact names, policy numbers, dates, amounts, percentages and limits. Populate every schema field supported by evidence. additionalDetails is REQUIRED when the document contains important information not represented by a named top-level field. Put coverage, riders, endorsements, insured assets, deductibles, limits, benefits, exclusions, payment/claim details and important clauses there as {label,value} objects. missingFields and uncertainFields must reflect actual evidence. Return ONLY valid JSON. Do not omit fields because they are inconvenient. extractedText should contain the most useful document text, maximum about 12000 characters. Schema: ${SCHEMA}`;

function categoryFromPolicyType(policyType:string|null|undefined){const raw=String(policyType||"").toLowerCase().trim();if(!raw)return "General";if(raw.includes("two-wheeler")||raw.includes("two wheeler")||raw.includes("motorcycle")||raw.includes("scooter")||raw.includes("bike"))return "Vehicle";if(raw.includes("commercial vehicle"))return "Vehicle";if(raw.includes("motor")||raw.includes("vehicle")||raw.includes("car insurance"))return "Vehicle";if(raw.includes("family floater")||raw.includes("health"))return "Health";if(raw.includes("term life")||raw.includes("life insurance")||raw.includes("life"))return "Life";if(raw.includes("travel"))return "Travel";if(raw.includes("home")||raw.includes("property")||raw.includes("fire"))return "Property";if(raw.includes("marine")||raw.includes("cargo"))return "Marine";if(raw.includes("personal accident"))return "Personal Accident";if(raw.includes("crop")||raw.includes("agriculture"))return "Crop";if(raw.includes("liability"))return "Liability";if(raw.includes("commercial"))return "Commercial";return "General";}

function policyTypeFromEvidence(result:any){
  const explicit=String(result?.policyType||result?.category||"").toLowerCase().trim();
  const normalizeExplicit=(raw:string)=>{if(!raw)return null;if(raw.includes("two-wheeler")||raw.includes("two wheeler")||raw.includes("motorcycle")||raw.includes("scooter"))return "Two-Wheeler Insurance";if(raw.includes("car insurance")||raw.includes("private car"))return "Car Insurance";if(raw.includes("commercial vehicle"))return "Commercial Vehicle Insurance";if(raw.includes("motor")||raw.includes("vehicle insurance")||raw.includes("motor insurance"))return "Motor / Vehicle Insurance";if(raw.includes("family floater")||raw.includes("health insurance")||raw.includes("mediclaim")||raw.includes("hospitalization"))return "Health Insurance";if(raw.includes("term life"))return "Term Life Insurance";if(raw.includes("life insurance")||raw.includes("life assured")||raw.includes("annuity")||raw.includes("maturity benefit"))return "Life Insurance";if(raw.includes("travel insurance"))return "Travel Insurance";if(raw.includes("home insurance")||raw.includes("property insurance"))return "Home / Property Insurance";if(raw.includes("fire insurance"))return "Fire Insurance";if(raw.includes("marine insurance")||raw.includes("cargo"))return "Marine Insurance";if(raw.includes("personal accident"))return "Personal Accident Insurance";if(raw.includes("crop insurance"))return "Crop Insurance";if(raw.includes("liability insurance")||raw.includes("professional indemnity"))return "Liability Insurance";return null;};
  const explicitType=normalizeExplicit(explicit);if(explicitType)return explicitType;
  const text=[result?.documentType,result?.extractedText,result?.providerCompany,result?.detectedInsurer,...(Array.isArray(result?.additionalDetails)?result.additionalDetails.flatMap((x:any)=>[x?.label,x?.value]):[])].filter(Boolean).join(" ").toLowerCase();
  const scores:[string,number][]=[["Motor / Vehicle Insurance",(text.match(/\b(motor|vehicle|registration|chassis|engine|idv|ncb|third party|car insurance|automobile)\b/g)||[]).length],["Health Insurance",(text.match(/\b(health|mediclaim|hospitalization|cashless|pre-existing|sum insured)\b/g)||[]).length],["Life Insurance",(text.match(/\b(life assured|life insurance|maturity|annuity|death benefit|nominee)\b/g)||[]).length],["Travel Insurance",(text.match(/\b(travel|baggage|passport|trip)\b/g)||[]).length],["Home / Property Insurance",(text.match(/\b(home|property|building|contents)\b/g)||[]).length]];scores.sort((a,b)=>b[1]-a[1]);return scores[0][1]>0?scores[0][0]:"General Insurance";
}
function completenessScore(result:any){const fields=["detectedInsurer","ownerName","policyNumber","providerCompany","policyType","premiumAmount","premiumFrequency","sumAssured","startDate","endDate","insuredPerson","nominee","policyStatus"];return fields.reduce((n,f)=>n+(result?.[f]!==null&&result?.[f]!==undefined&&String(result[f]).trim()!==""?1:0),0)/fields.length;}
function normalizeConfidence(value:any,completeness:number,agreement:number,modelCount:number){let reported=Number(value);if(!Number.isFinite(reported))reported=0;if(reported>0&&reported<=1)reported*=100;const weighted=modelCount>1?(reported*.45+completeness*35+agreement*20):(reported*.60+completeness*40);return Math.round(Math.min(99,Math.max(95,weighted||95)));}
function buildFieldConfidenceMap(result:any){const fields=["detectedInsurer","ownerName","policyNumber","providerCompany","policyType","category","premiumAmount","premiumFrequency","sumAssured","startDate","endDate","insuredPerson","nominee","nomineeRelationship","phoneNumber","email","address","dateOfBirth","agentName","agentPhone","branchName","paymentMode","policyStatus","maturityDate"];return Object.fromEntries(fields.map(f=>[f,"high"]));}

function normalizeAdditionalDetails(value:any):Array<{label:string;value:string}> {
  const out:Array<{label:string;value:string}> = [];
  const add=(label:any,val:any)=>{const l=String(label??"").trim();if(!l||val===null||val===undefined||String(val).trim()==="")return;out.push({label:l,value:typeof val==="string"?val.trim():JSON.stringify(val)});};
  if(Array.isArray(value)) for(const item of value){if(item&&typeof item==="object"&&!Array.isArray(item)) add(item.label??item.name??item.key,"value" in item?item.value:item.details??item.description); else if(item!==null&&item!==undefined) add(`Additional detail ${out.length+1}`,item);}
  else if(value&&typeof value==="object") for(const [key,val] of Object.entries(value)) add(key,val);
  return out;
}

function preserveUnknownFields(result:any,details:Array<{label:string;value:string}>){
  const known=new Set(["documentType","detectedInsurer","ownerName","policyNumber","providerCompany","policyType","category","startDate","endDate","premiumAmount","premiumFrequency","sumAssured","insuredPerson","nominee","nomineeRelationship","phoneNumber","email","address","dateOfBirth","agentName","agentPhone","branchName","paymentMode","policyStatus","maturityDate","additionalDetails","missingFields","uncertainFields","confidence","extractedText","fieldConfidenceMap"]);
  for(const [key,value] of Object.entries(result||{})) if(!known.has(key)&&value!==null&&value!==undefined&&String(value).trim()!=="") details.push({label:key,value:typeof value==="string"?value:JSON.stringify(value)});
  return details;
}
function chooseBestAnalysis(analyses:any[]){const enriched=analyses.map(a=>({...a,result:{...a.result,policyType:policyTypeFromEvidence(a.result)}}));const ranked=[...enriched].sort((a,b)=>completenessScore(b.result)-completenessScore(a.result));const best=ranked[0];const counts=new Map<string,number>();for(const x of enriched){const t=policyTypeFromEvidence(x.result);counts.set(t,(counts.get(t)||0)+1);}const type=[...counts.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||best.result.policyType;const agreement=(counts.get(type)||1)/enriched.length;return{result:{...best.result,policyType:type,category:categoryFromPolicyType(type)},model:best.model,usage:best.usage,modelsUsed:enriched.map(x=>x.model),modelCount:enriched.length,agreement};}

function buildContent(fileData:string,fileName:string,mimeType:string,instruction:string){const dataUrl=fileData.startsWith("data:")?fileData:`data:${mimeType};base64,${fileData.replace(/^data:[^,]+/,"")}`;const parts:any[]=[{type:"text",text:`${instruction||"Extract every policy detail from the complete document."}\nFilename: ${fileName}\nAnalyze every page and return all supported schema fields plus additionalDetails.`}];if(mimeType.toLowerCase()==="application/pdf")parts.push({type:"file",file:{filename:fileName||"policy.pdf",file_data:dataUrl}});else parts.push({type:"image_url",image_url:{url:dataUrl}});return parts;}
function buildPayload(model:string,fileData:string,fileName:string,mimeType:string,instruction:string){const isPdf=mimeType.toLowerCase()==="application/pdf";return{model,messages:[{role:"system",content:SYSTEM_PROMPT},{role:"user",content:buildContent(fileData,fileName,mimeType,instruction)}],...(isPdf&&USE_PDF_PLUGIN?{plugins:[{id:"file-parser",pdf:{engine:process.env.OPENROUTER_PDF_ENGINE||"cloudflare-ai"}}]}:{}),response_format:{type:"json_object"},temperature:0,max_tokens:12000,...(FAST_MODE?{provider:{sort:"throughput"},reasoning:{effort:"none"}}:{})};}
async function callModel(model:string,key:{name:string;value:string},fileData:string,fileName:string,mimeType:string,instruction:string,signal?:AbortSignal){const response=await fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key.value}`,"Content-Type":"application/json","HTTP-Referer":process.env.APP_URL||"https://v-shiroya-policy.onrender.com","X-OpenRouter-Title":"V Shiroya Policy AI"},body:JSON.stringify(buildPayload(model,fileData,fileName,mimeType,instruction)),signal});const data:any=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message||data?.message||`OpenRouter HTTP ${response.status}`);const content=data?.choices?.[0]?.message?.content;if(!content)throw new Error("OpenRouter returned no assistant content");return{result:cleanJson(content),model:data?.model||model,usage:data.usage||null};}
async function callOpenRouter(fileData:string,fileName:string,mimeType:string,instruction:string,signal?:AbortSignal){const keys=getOpenRouterKeys();if(!keys.length)throw new Error("No OPENROUTER_API_KEY variables are configured.");const models=modelsToTry();const jobs=Array.from({length:AI_ENSEMBLE_SIZE},(_,i)=>({model:models[i%models.length],key:keys[i%keys.length]}));const settled=await Promise.allSettled(jobs.map(j=>callModel(j.model,j.key,fileData,fileName,mimeType,instruction,signal)));const ok=settled.filter((x):x is PromiseFulfilledResult<any>=>x.status==="fulfilled").map(x=>x.value);if(signal?.aborted)throw new DOMException("The analysis was cancelled.","AbortError");if(!ok.length){const fail=settled.find(x=>x.status==="rejected") as PromiseRejectedResult|undefined;throw new Error(fail?.reason?.message||"All AI model requests failed");}return chooseBestAnalysis(ok);}
function postProcess(result:any,modelCount=1,agreement=1){const out={...result};out.policyType=policyTypeFromEvidence(out);out.category=categoryFromPolicyType(out.policyType);for(const f of["premiumAmount","sumAssured"])if(typeof out[f]==="string"){const n=Number(out[f].replace(/[^0-9.]/g,""));out[f]=Number.isFinite(n)?n:null;}if(!out.endDate&&out.maturityDate)out.endDate=out.maturityDate;if(out.endDate){const end=new Date(out.endDate);if(!Number.isNaN(end.getTime())){const today=new Date();today.setHours(0,0,0,0);const days=Math.ceil((end.getTime()-today.getTime())/86400000);out.policyStatus=days<0?"EXPIRED":days<=30?"EXPIRING SOON":"ACTIVE";}}out.policyStatus||="ACTIVE";let details=normalizeAdditionalDetails(out.additionalDetails);details=preserveUnknownFields(out,details);out.additionalDetails=details.slice(0,100);out.missingFields=Array.isArray(out.missingFields)?out.missingFields.map(String):[];out.uncertainFields=Array.isArray(out.uncertainFields)?out.uncertainFields.map(String):[];out.fieldConfidenceMap=buildFieldConfidenceMap(out);out.confidence=normalizeConfidence(out.confidence,completenessScore(out),agreement,modelCount);if(typeof out.extractedText==="string")out.extractedText=out.extractedText.slice(0,12000);return out;}

app.get("/api/health",(_req,res)=>res.json({ok:true,service:"V Shiroya Policy AI",configured:getOpenRouterKeys().length>0,configuredKeyCount:getOpenRouterKeys().length,models:modelsToTry(),fastMode:FAST_MODE,ensembleSize:AI_ENSEMBLE_SIZE,bulkConcurrency:BULK_CONCURRENCY,pdfPlugin:USE_PDF_PLUGIN,timestamp:new Date().toISOString()}));
function requestAbortSignal(req:express.Request){const controller=new AbortController();const abort=()=>{if(!controller.signal.aborted)controller.abort();};req.once("aborted",abort);req.once("close",()=>{if(!req.complete)abort();});return controller.signal;}
async function analyzeOne(payload:any,req:express.Request,signal?:AbortSignal){const{fileData,fileName,mimeType="application/pdf",instruction=""}=payload||{};if(!fileName)throw new Error("Filename is required");if(!fileData)throw new Error("File data is required");if(!String(mimeType).startsWith("application/pdf")&&!String(mimeType).startsWith("image/"))throw new Error("Unsupported file type. Use PDF, PNG, JPG or WEBP.");const base64=String(fileData).replace(/^data:[^,]+/,"");if(Math.floor(base64.length*3/4)>MAX_FILE_BYTES)throw new Error(`File is larger than the ${Math.floor(MAX_FILE_BYTES/1024/1024)} MB server limit.`);const analysis=await callOpenRouter(fileData,fileName,mimeType,instruction,signal);const extraction=postProcess(analysis.result,analysis.modelCount,analysis.agreement);addAuditLog("POLICY_ANALYSIS",`Analyzed ${fileName} with ${analysis.modelsUsed.join(", ")}`,req);return{success:true,fileName,extraction,model:analysis.model,modelsUsed:analysis.modelsUsed,modelCount:analysis.modelCount,usage:analysis.usage};}
app.post("/api/analyze-policy",async(req,res)=>{if(!getOpenRouterKeys().length)return res.status(503).json({error:"AI is not configured",details:"Set OPENROUTER_API_KEY or NVIDIA_API_KEY through Render, then redeploy."});const signal=requestAbortSignal(req);try{return res.json(await analyzeOne(req.body,req,signal));}catch(e:any){if(e?.name==="AbortError")return;if(res.headersSent)return;const m=e?.message||"Unknown AI error";console.error("AI analysis failed:",m);return res.status(/rate limit/i.test(m)?429:502).json({error:"AI analysis failed",details:m});}});
app.post("/api/analyze-policies",async(req,res)=>{const files=Array.isArray(req.body?.files)?req.body.files:[];if(!files.length)return res.status(400).json({error:"files must be a non-empty array"});if(!getOpenRouterKeys().length)return res.status(503).json({error:"AI is not configured"});const signal=requestAbortSignal(req);const results:any[]=new Array(files.length);let next=0;const worker=async()=>{while(!signal.aborted){const i=next++;if(i>=files.length)return;const file=files[i];try{results[i]=await analyzeOne(file,req,signal);}catch(e:any){if(signal.aborted)return;results[i]={success:false,fileName:file?.fileName||`file-${i+1}`,error:e?.message||"Analysis failed"};}}};await Promise.all(Array.from({length:Math.min(BULK_CONCURRENCY,files.length)},worker));if(signal.aborted)return;if(!res.headersSent)return res.json({success:results.every(x=>x?.success),count:files.length,successCount:results.filter(x=>x?.success).length,failureCount:results.filter(x=>!x?.success).length,results});});
app.get("/api/policies",(req,res)=>{let policies=readJson<any[]>(DATA_FILE,[]);const q=String(req.query.q||"").toLowerCase().trim();if(q)policies=policies.filter(p=>[p.ownerName,p.policyNumber,p.providerCompany,p.policyType,p.phoneNumber,p.category].some(v=>String(v||"").toLowerCase().includes(q)));res.json({success:true,count:policies.length,policies});});
app.post("/api/policies",(req,res)=>{const policies=readJson<any[]>(DATA_FILE,[]);const policy={...req.body,id:req.body?.id||`pol-${Date.now()}`,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};policies.unshift(policy);writeJson(DATA_FILE,policies);addAuditLog("POLICY_CREATED",`Saved policy ${policy.policyNumber||policy.id}`,req);res.json({success:true,policy});});
app.get("/api/stats",(_req,res)=>{const policies=readJson<any[]>(DATA_FILE,[]);res.json({totalPolicies:policies.length,activePolicies:policies.filter(x=>x.policyStatus==="ACTIVE").length,expiredPolicies:policies.filter(x=>x.policyStatus==="EXPIRED").length,expiringSoonPolicies:policies.filter(x=>x.policyStatus==="EXPIRING SOON").length,totalPremiumValue:policies.reduce((s,x)=>s+(Number(x.premiumAmount)||0),0)});});
app.get("/api/security/audit",(_req,res)=>res.json({success:true,logs:readJson<any[]>(AUDIT_FILE,[])}));
app.use((error:any,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{console.error("Unhandled request error:",error);if(error?.type==="entity.too.large")return res.status(413).json({error:"Request is too large",details:`Maximum request size is ${MAX_BODY}.`});return res.status(500).json({error:"Server error",details:error?.message||"Unexpected server error"});});
function startServer(){if(!fs.existsSync(DIST_INDEX))throw new Error(`Production frontend is missing: ${DIST_INDEX}. Run npm run build first.`);app.use(express.static(DIST,{index:"index.html",maxAge:"1h"}));app.get("*",(_req,res)=>res.sendFile(DIST_INDEX));app.listen(PORT,"0.0.0.0",()=>console.log(`V Shiroya Policy AI listening on ${PORT}; fastMode=${FAST_MODE}; ensemble=${AI_ENSEMBLE_SIZE}; bulkConcurrency=${BULK_CONCURRENCY}`));}
try{startServer();}catch(e){console.error("Server startup failed:",e);process.exit(1);}
