import { useEffect, useState } from "react";

type Result = Record<string, any>;
const fields = [["Policy holder","ownerName"],["Policy number","policyNumber"],["Insurer","providerCompany"],["Policy type","policyType"],["Start date","startDate"],["End date","endDate"],["Premium","premiumAmount"],["Frequency","premiumFrequency"],["Sum assured","sumAssured"],["Insured person","insuredPerson"],["Nominee","nominee"],["Nominee relation","nomineeRelationship"],["Phone","phoneNumber"],["Email","email"],["DOB","dateOfBirth"],["Agent","agentName"],["Branch","branchName"],["Payment mode","paymentMode"],["Maturity","maturityDate"]] as const;

export default function App(){
 const [file,setFile]=useState<File|null>(null),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[health,setHealth]=useState<any>(null);
 const instruction="Extract every policy detail, coverage, premium, nominee, dates, riders, endorsements and important clauses. Never guess missing values.";
 useEffect(()=>{fetch('/api/health').then(r=>r.json()).then(setHealth).catch(()=>setHealth({configured:false}))},[]);
 async function analyze(){if(!file)return;setBusy(true);setError("");setResult(null);try{const data=await new Promise<string>((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result));r.onerror=no;r.readAsDataURL(file)});const r=await fetch('/api/analyze-policy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fileData:data,fileName:file.name,mimeType:file.type||'application/pdf',instruction})});const d=await r.json();if(!r.ok)throw Error(d.details||d.error||'Analysis failed');setResult(d.extraction)}catch(e:any){setError(e.message||'Analysis failed')}finally{setBusy(false)}}
 return <div className="app"><header><div><b>V SHIROYA <span>POLICY AI</span></b><small>Insurance document intelligence & audit</small></div><label className={health?.configured?'ready':'notready'}>● {health?.configured?'AI ready':'AI key not configured'}</label></header><main><section className="hero"><div><small>MULTIMODAL POLICY ANALYZER</small><h1>Turn policy documents into <em>actionable intelligence.</em></h1><p>Upload a PDF or policy image for full-document OCR, structured extraction and audit analysis.</p></div><aside>{health?.models?.[0]||'OpenRouter'}<small>Active AI model</small></aside></section><div className="workspace"><section className="panel"><div className="title"><h2>01 · Upload document</h2><label>Choose file<input type="file" accept="application/pdf,image/png,image/jpeg,image/webp" onChange={e=>{setFile(e.target.files?.[0]||null);setResult(null);setError('')}}/></label></div><div className="drop">{file?'✓':'↑'}<strong>{file?file.name:'Drop your policy here'}</strong><small>{file?`${(file.size/1048576).toFixed(2)} MB · ${file.type||'document'}`:'PDF, PNG, JPG or WEBP · up to 100 MB'}</small></div><button disabled={!file||busy} onClick={analyze}>{busy?'Analyzing document…':'Analyze policy →'}</button>{error&&<div className="error">{error}</div>}<p className="note">Your OpenRouter key stays server-side.</p></section><section className="panel"><div className="title"><h2>02 · Analysis result</h2>{result&&<label className="status">{result.policyStatus}</label>}</div>{!result&&!busy&&<div className="empty"><b>✦</b><h3>Waiting for a document</h3><p>Upload a policy and start analysis.</p></div>}{busy&&<div className="empty"><b>✦</b><h3>Reading your policy…</h3><p>OCR, layout analysis and extraction are running.</p></div>}{result&&<div><div className="confidence"><b>{result.confidence??0}%</b><span>AI confidence</span></div><div className="grid">{fields.map(([l,k])=><div className="field" key={k}><small>{l}</small><strong>{result[k]??'Not available'}</strong></div>)}</div>{result.additionalDetails?.length>0&&<><h3>Additional details</h3>{result.additionalDetails.map((x:any,i:number)=><div className="detail" key={i}><b>{x.label}</b><span>{x.value}</span></div>)}</>}<details><summary>Extracted text</summary><pre>{result.extractedText||'No extracted text returned.'}</pre></details></div>}</section></div></main><footer>V Shiroya Policy AI · Server-side OpenRouter analysis</footer></div>
}
